'use strict';

const PROVIDERS = Object.freeze({
  'coinbase-exchange-v1': Object.freeze({
    provider_id: 'coinbase-exchange-v1',
    parser_id: 'coinbase-exchange-ticker-v1',
    asset: 'ZEC',
    asset_id: 'zec-zcash',
    quote_currency: 'USD',
    method: 'GET',
    url: 'https://api.exchange.coinbase.com/products/ZEC-USD/ticker',
    hostname: 'api.exchange.coinbase.com',
    path: '/products/ZEC-USD/ticker',
    enabled_by_default: false,
    tls_min_version: 'TLSv1.2',
    accept: 'application/json',
    accept_encoding: 'identity',
    max_redirects: 0,
    connect_timeout_ms: 5000,
    overall_timeout_ms: 10000,
    max_header_bytes: 16384,
    max_body_bytes: 65536,
    port: 443,
  }),
  'kraken-spot-v1': Object.freeze({
    provider_id: 'kraken-spot-v1',
    parser_id: 'kraken-spot-ticker-v1',
    asset: 'XMR',
    asset_id: 'xmr-monero',
    quote_currency: 'USD',
    method: 'GET',
    url: 'https://api.kraken.com/0/public/Ticker?pair=XMRUSD',
    hostname: 'api.kraken.com',
    path: '/0/public/Ticker?pair=XMRUSD',
    result_pair: 'XXMRZUSD',
    request_pair: 'XMRUSD',
    enabled_by_default: false,
    tls_min_version: 'TLSv1.2',
    accept: 'application/json',
    accept_encoding: 'identity',
    max_redirects: 0,
    connect_timeout_ms: 5000,
    overall_timeout_ms: 10000,
    max_header_bytes: 16384,
    max_body_bytes: 65536,
    port: 443,
  }),
});

module.exports = { PROVIDERS };
